# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CourseList', '0003_auto_20160302_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('assignmentID', models.AutoField(primary_key=True, serialize=False)),
                ('assignMarks1', models.IntegerField(default=0, verbose_name='Assignment1 Marks')),
                ('assignMarks2', models.IntegerField(default=0, verbose_name='Assignment2 Marks')),
                ('assignMarks3', models.IntegerField(default=0, verbose_name='Assignment3 Marks')),
                ('assignMarks4', models.IntegerField(default=0, verbose_name='Assignment4 Marks')),
                ('assignMarks5', models.IntegerField(default=0, verbose_name='Assignment5 Marks')),
                ('assignMarks6', models.IntegerField(default=0, verbose_name='Assignment6 Marks')),
                ('assignMarks7', models.IntegerField(default=0, verbose_name='Assignment7 Marks')),
                ('assignMarks8', models.IntegerField(default=0, verbose_name='Assignment8 Marks')),
                ('courseID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CourseList.CourseList')),
                ('studentID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CourseList.StudentRegistration')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('ContentID', models.AutoField(primary_key=True, serialize=False)),
                ('Lecture1', models.CharField(max_length=10, null=True, verbose_name='Lecture1')),
                ('Lecture2', models.CharField(max_length=10, null=True, verbose_name='Lecture2')),
                ('Lecture3', models.CharField(max_length=10, null=True, verbose_name='Lecture3')),
                ('Lecture4', models.CharField(max_length=10, null=True, verbose_name='Lecture4')),
                ('Lecture5', models.CharField(max_length=10, null=True, verbose_name='Lecture5')),
                ('Lecture6', models.CharField(max_length=10, null=True, verbose_name='Lecture6')),
                ('Lecture7', models.CharField(max_length=10, null=True, verbose_name='Lecture7')),
                ('Lecture8', models.CharField(max_length=10, null=True, verbose_name='Lecture8')),
                ('Assignment1', models.CharField(max_length=10, null=True, verbose_name='Assignment1')),
                ('Assignment2', models.CharField(max_length=10, null=True, verbose_name='Assignment2')),
                ('Assignment3', models.CharField(max_length=10, null=True, verbose_name='Assignment3')),
                ('Assignment4', models.CharField(max_length=10, null=True, verbose_name='Assignment4')),
                ('Assignment5', models.CharField(max_length=10, null=True, verbose_name='Assignment5')),
                ('Assignment6', models.CharField(max_length=10, null=True, verbose_name='Assignment6')),
                ('Assignment7', models.CharField(max_length=10, null=True, verbose_name='Assignment7')),
                ('Assignment8', models.CharField(max_length=10, null=True, verbose_name='Assignment8')),
                ('Test1', models.CharField(max_length=10, null=True, verbose_name='Test1')),
                ('Test2', models.CharField(max_length=10, null=True, verbose_name='Test2')),
                ('Test3', models.CharField(max_length=10, null=True, verbose_name='Test3')),
                ('Test4', models.CharField(max_length=10, null=True, verbose_name='Test4')),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CourseList.CourseList')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('assignmentID', models.AutoField(primary_key=True, serialize=False)),
                ('testMarks1', models.IntegerField(default=0, verbose_name='Test1 Marks')),
                ('testMarks2', models.IntegerField(default=0, verbose_name='Test2 Marks')),
                ('testMarks3', models.IntegerField(default=0, verbose_name='Test3 Marks')),
                ('testMarks4', models.IntegerField(default=0, verbose_name='Test4 Marks')),
                ('courseID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CourseList.CourseList')),
                ('studentID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CourseList.StudentRegistration')),
            ],
        ),
    ]
