# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='Assignment1',
            field=models.CharField(max_length=100, null=True, verbose_name='Assignment1'),
        ),
        migrations.AlterField(
            model_name='content',
            name='Assignment2',
            field=models.CharField(max_length=100, null=True, verbose_name='Assignment2'),
        ),
        migrations.AlterField(
            model_name='content',
            name='Assignment3',
            field=models.CharField(max_length=100, null=True, verbose_name='Assignment3'),
        ),
        migrations.AlterField(
            model_name='content',
            name='Assignment4',
            field=models.CharField(max_length=100, null=True, verbose_name='Assignment4'),
        ),
        migrations.AlterField(
            model_name='content',
            name='Assignment5',
            field=models.CharField(max_length=100, null=True, verbose_name='Assignment5'),
        ),
        migrations.AlterField(
            model_name='content',
            name='Assignment6',
            field=models.CharField(max_length=100, null=True, verbose_name='Assignment6'),
        ),
        migrations.AlterField(
            model_name='content',
            name='Assignment7',
            field=models.CharField(max_length=100, null=True, verbose_name='Assignment7'),
        ),
        migrations.AlterField(
            model_name='content',
            name='Assignment8',
            field=models.CharField(max_length=100, null=True, verbose_name='Assignment8'),
        ),
        migrations.AlterField(
            model_name='content',
            name='Lecture1',
            field=models.CharField(max_length=100, null=True, verbose_name='Lecture1'),
        ),
        migrations.AlterField(
            model_name='content',
            name='Lecture2',
            field=models.CharField(max_length=100, null=True, verbose_name='Lecture2'),
        ),
        migrations.AlterField(
            model_name='content',
            name='Lecture3',
            field=models.CharField(max_length=100, null=True, verbose_name='Lecture3'),
        ),
        migrations.AlterField(
            model_name='content',
            name='Lecture4',
            field=models.CharField(max_length=100, null=True, verbose_name='Lecture4'),
        ),
        migrations.AlterField(
            model_name='content',
            name='Lecture5',
            field=models.CharField(max_length=100, null=True, verbose_name='Lecture5'),
        ),
        migrations.AlterField(
            model_name='content',
            name='Lecture6',
            field=models.CharField(max_length=100, null=True, verbose_name='Lecture6'),
        ),
        migrations.AlterField(
            model_name='content',
            name='Lecture7',
            field=models.CharField(max_length=100, null=True, verbose_name='Lecture7'),
        ),
        migrations.AlterField(
            model_name='content',
            name='Lecture8',
            field=models.CharField(max_length=100, null=True, verbose_name='Lecture8'),
        ),
        migrations.AlterField(
            model_name='content',
            name='Test1',
            field=models.CharField(max_length=100, null=True, verbose_name='Test1'),
        ),
        migrations.AlterField(
            model_name='content',
            name='Test2',
            field=models.CharField(max_length=100, null=True, verbose_name='Test2'),
        ),
        migrations.AlterField(
            model_name='content',
            name='Test3',
            field=models.CharField(max_length=100, null=True, verbose_name='Test3'),
        ),
        migrations.AlterField(
            model_name='content',
            name='Test4',
            field=models.CharField(max_length=100, null=True, verbose_name='Test4'),
        ),
    ]
