# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 19:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('People', '0001_initial'),
        ('CourseList', '0002_auto_20160301_0059'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('week', models.AutoField(primary_key=True, serialize=False)),
                ('assignMarks1', models.IntegerField()),
                ('assignMarks2', models.IntegerField()),
                ('assignMarks3', models.IntegerField()),
                ('assignMarks4', models.IntegerField()),
                ('assignMarks5', models.IntegerField()),
                ('assignMarks6', models.IntegerField()),
                ('assignMarks7', models.IntegerField()),
                ('assignMarks8', models.IntegerField()),
                ('studentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='People.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('week', models.AutoField(primary_key=True, serialize=False)),
                ('lectures', models.CharField(max_length=10000)),
                ('assignment', models.CharField(max_length=10000)),
                ('tests', models.CharField(max_length=10000)),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CourseList.CourseList')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('week', models.AutoField(primary_key=True, serialize=False)),
                ('testMarks1', models.IntegerField()),
                ('testMarks2', models.IntegerField()),
                ('testMarks3', models.IntegerField()),
                ('studentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='People.Student')),
            ],
        ),
    ]
