# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 18:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('People', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseList',
            fields=[
                ('courseID', models.AutoField(primary_key=True, serialize=False)),
                ('courseName', models.CharField(max_length=100)),
                ('startDate', models.DateTimeField(verbose_name='Start Date')),
                ('endDate', models.DateTimeField(verbose_name='End Date')),
                ('faculty1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courselist_courselist_related', to='People.Faculty')),
                ('faculty2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='People.Faculty')),
            ],
        ),
        migrations.CreateModel(
            name='StudentRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CourseList.CourseList')),
                ('studentID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='People.Student')),
            ],
        ),
    ]
