# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 16:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('adminID', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('adminUserName', models.CharField(max_length=100)),
                ('adminPassword', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('facultyID', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('dob', models.DateTimeField(verbose_name='Date of Birth')),
                ('age', models.IntegerField()),
                ('facultyUserName', models.CharField(max_length=100)),
                ('facultyPassword', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('parentID', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('parentUserName', models.CharField(max_length=100)),
                ('parentPassword', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentID', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('dob', models.DateTimeField(verbose_name='Date of Birth')),
                ('age', models.IntegerField()),
                ('studentUserName', models.CharField(max_length=100)),
                ('studentPassword', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='People.Parent')),
                ('studentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='People.Student')),
            ],
        ),
    ]
