# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 14:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('People', '0002_auto_20160302_1632'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student_Parent',
            new_name='StudentParent',
        ),
    ]
