# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 14:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mail', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student_Faculty_Mail',
            new_name='FacultyStudentMail',
        ),
        migrations.RenameModel(
            old_name='Faculty_Student_Mail',
            new_name='StudentFacultyMail',
        ),
    ]
